# Site settings
title: loren.io
name: loren.io
email: lh@loren.io
description: > # this means to ignore newlines until "baseurl:"
  Writing, projects, and randomness courtesy of Loren Hoffman.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://loren.io" # the base hostname & protocol for your site
permalink: /:categories/:title/
highlighter: rouge

# Build settings
markdown: kramdown
